In [1]:
import pandas as pd

In [159]:
def read_directed():
    df = pd.read_csv("directed_graphs.csv").drop("Unnamed: 0", axis=1)
    df["persistence"]/=df["num_edges"]
    df["triangles"]/=(df["num_nodes"]*df["num_times"]*3)
    return df

def read_undirected():
    df = pd.read_csv("undirected_graphs.csv").drop("Unnamed: 0", axis=1)
    df["persistence"]/=df["num_edges"]
    df["triangles"]/=(df["num_nodes"]*df["num_times"]*6)
    return df

df = pd.concat([read_directed(), read_undirected()])

In [160]:
keep_properties = ["triangles"]
l = ["abbr", "depth"]+keep_properties
l

['abbr', 'depth', 'triangles']

In [161]:
df2 = df.groupby(["abbr", "depth"]).agg(["mean", "std"]).drop("seed", axis=1)
df2 = df2.reset_index()
#df.unstack("depth")

In [162]:

d = {"wea":0, "ht09":1, "wp":2, "pri":3, "rac":4, "talk_eo":5, "dnc":6, "fb":7, "eu2":8,"eu3":9} | {i:i for i in range(-10,10)}
df2.sort_values(by=['abbr', "depth"], key=lambda x: x.map(d))

       abbr depth      B_in                   B_out                       B  \
                       mean           std      mean           std      mean
32      wea    -1  0.823085           NaN  0.823085           NaN  0.823085
33      wea     0  0.823085  3.700743e-17  0.823085  3.700743e-17  0.823085
34      wea     1  0.823085  3.700743e-17  0.823085  3.700743e-17  0.823085
35      wea     4  0.823085  0.000000e+00  0.823085  0.000000e+00  0.823085
16     ht09    -1  0.794695           NaN  0.794695           NaN  0.794695
17     ht09     0  0.794695  0.000000e+00  0.794695  0.000000e+00  0.794695
18     ht09     1  0.794695  0.000000e+00  0.794695  0.000000e+00  0.794695
19     ht09     4  0.794695  0.000000e+00  0.794695  0.000000e+00  0.794695
36       wp    -1  0.732547           NaN  0.732547           NaN  0.732547
37       wp     0  0.732547  6.409876e-17  0.732547  6.409876e-17  0.732547
38       wp     1  0.732547  0.000000e+00  0.732547  0.000000e+00  0.732547
39       wp     4  0.732547  0.000000e+00  0.732547  0.000000e+00  0.732547
20      pri    -1  0.570732           NaN  0.570732           NaN  0.570732
21      pri     0  0.570732  3.700743e-17  0.570732  3.700743e-17  0.570732
22      pri     1  0.570732  0.000000e+00  0.570732  0.000000e+00  0.570732
23      pri     2  0.570732  0.000000e+00  0.570732  0.000000e+00  0.570732
24      rac    -1  0.458448           NaN  0.458448           NaN  0.458448
25      rac     0  0.458448  5.551115e-17  0.458448  5.551115e-17  0.458448
26      rac     1  0.458448  0.000000e+00  0.458448  0.000000e+00  0.458448
27      rac     3  0.458448  0.000000e+00  0.458448  0.000000e+00  0.458448
28  talk_eo    -1  0.745688           NaN  0.627421           NaN  0.726500
29  talk_eo     0  0.745688  0.000000e+00 -0.023736  1.861038e-03  0.273557
30  talk_eo     1  0.745688  0.000000e+00  0.495285  1.186058e-03  0.616862
31  talk_eo     3  0.745688  0.000000e+00  0.663559  5.660867e-04  0.748184
0       dnc    -1  0.862304           NaN  0.821486           NaN  0.855377
1       dnc     0  0.862304  0.000000e+00  0.637293  2.074921e-03  0.727683
2       dnc     1  0.862305  0.000000e+00  0.819585  2.585076e-03  0.848402
3       dnc     4  0.862305  0.000000e+00  0.844317  4.148017e-04  0.867361
12       fb    -1  0.631417           NaN  0.536934           NaN  0.612836
13       fb     0  0.631417  0.000000e+00  0.269640  3.576999e-03  0.414823
14       fb     1  0.631554  0.000000e+00  0.546736  4.563794e-03  0.612039
15       fb     4  0.631554  0.000000e+00  0.531867  3.767258e-03  0.612126
4       eu2    -1  0.758320           NaN  0.740940           NaN  0.811241
5       eu2     0  0.758320  0.000000e+00  0.697773  1.204628e-03  0.779535
6       eu2     1  0.758373  0.000000e+00  0.745818  3.410584e-03  0.815305
7       eu2     4  0.758373  0.000000e+00  0.741944  1.025766e-03  0.812284
8       eu3    -1  0.665893           NaN  0.646170           NaN  0.735337
9       eu3     0  0.665893  0.000000e+00  0.591016  1.954468e-03  0.698289
10      eu3     1  0.665893  0.000000e+00  0.644354  3.881651e-03  0.734676
11      eu3     3  0.665893  0.000000e+00  0.646701  6.770564e-04  0.735975

                     triangles                c_triangles                \
             std          mean           std         mean           std
32           NaN  2.013679e-01           NaN          0.0           NaN
33  3.700743e-17  1.241915e-01  1.174662e-03          0.0  0.000000e+00
34  3.700743e-17  1.837421e-01  1.125553e-03          0.0  0.000000e+00
35  0.000000e+00  2.009770e-01  1.595499e-04          0.0  0.000000e+00
16           NaN  1.571757e+02           NaN   43387159.0           NaN
17  0.000000e+00  7.690081e+01  3.380459e+00   22799097.3  1.039530e+06
18  0.000000e+00  1.571710e+02  5.911729e-03   43386322.6  1.244498e+03
19  0.000000e+00  1.571780e+02  2.391382e-03   43387702.3  5.504303e+02
36           NaN  3.580764e+01           NaN   12526661.0           NaN
37  6.409876e-17  2.317766e+01  5.539136e+00    7814613.0  1.719274e+06
38  0.000000e+00  3.580764e+01  0.000000e+00   12526661.0  0.000000e+00
39  0.000000e+00  3.580764e+01  0.000000e+00   12526661.0  0.000000e+00
20           NaN  7.823684e+02           NaN     138221.0           NaN
21  3.700743e-17  7.737019e+02  2.285016e+00     139619.6  1.063600e+03
22  0.000000e+00  7.826648e+02  2.526585e-01     138371.9  9.345403e+01
23  0.000000e+00  7.824832e+02  1.757254e-01     138255.1  4.262615e+01
24           NaN  1.151350e+03           NaN     626895.0           NaN
25  5.551115e-17  1.141053e+03  6.544136e+00     652294.8  4.322800e+03
26  0.000000e+00  1.150293e+03  7.448948e-01     626675.4  3.441021e+02
27  0.000000e+00  1.151350e+03  0.000000e+00     626895.0  0.000000e+00
28           NaN  1.498745e-01           NaN   18718274.0           NaN
29  1.077961e-03  1.389625e-07  2.168737e-08         17.2  4.184628e+00
30  7.340191e-04  1.518241e-01  1.343042e-03   19081098.2  1.583003e+05
31  5.542572e-04  1.499015e-01  2.874651e-05   18722145.6  4.024742e+03
0            NaN  1.921779e+00           NaN   34350493.0           NaN
1   1.450873e-03  4.163310e-05  2.894979e-06        730.9  6.030745e+01
2   2.079471e-03  2.515913e+00  1.162751e-02   44124161.1  1.952702e+05
3   6.358805e-04  2.637564e+00  4.819025e-04   46200432.6  7.743923e+03
12           NaN  1.475322e-03           NaN      21785.0           NaN
13  2.415192e-03  5.530441e-04  1.699347e-05       8328.4  2.835404e+02
14  1.101517e-03  1.091458e-03  8.948171e-05      17177.5  1.499126e+03
15  8.826847e-04  1.461961e-03  1.055617e-05      21515.0  2.357739e+02
4            NaN  2.910614e+02           NaN  768179307.0           NaN
5   7.620289e-04  1.346410e+00  3.268688e-02    3529165.9  8.396956e+04
6   1.506629e-03  3.225596e+02  7.077484e-01  854663630.4  2.045575e+06
7   5.569120e-04  3.387255e+02  7.580333e-02  897899301.1  1.505443e+05
8            NaN  9.035909e+00           NaN    3647777.0           NaN
9   8.704005e-04  9.641949e-01  3.698923e-02     382360.2  1.446946e+04
10  2.188497e-03  8.060086e+00  9.662227e-02    3270929.8  3.621218e+04
11  2.607382e-04  9.155318e+00  2.074453e-02    3720351.8  8.663850e+03

   persistence           num_times      num_edges      num_nodes
          mean       std      mean  std      mean  std      mean  std
32    0.000000       NaN      23.0  NaN    1333.0  NaN     445.0  NaN
33    0.000000  0.000000      23.0  0.0    1333.0  0.0     445.0  0.0
34    0.000000  0.000000      23.0  0.0    1333.0  0.0     445.0  0.0
35    0.000000  0.000000      23.0  0.0    1333.0  0.0     445.0  0.0
16    0.890600       NaN    5246.0  NaN   20818.0  NaN     113.0  NaN
17    0.226827  0.033903    5246.0  0.0   20818.0  0.0     113.0  0.0
18    0.889892  0.000366    5246.0  0.0   20818.0  0.0     113.0  0.0
19    0.890485  0.000099    5246.0  0.0   20818.0  0.0     113.0  0.0
36    1.175970       NaN    7104.0  NaN    9827.0  NaN      92.0  NaN
37    0.843146  0.153785    7104.0  0.0    9827.0  0.0      92.0  0.0
38    1.175970  0.000000    7104.0  0.0    9827.0  0.0      92.0  0.0
39    1.175970  0.000000    7104.0  0.0    9827.0  0.0      92.0  0.0
20    0.084095       NaN      19.0  NaN    1340.0  NaN      25.0  NaN
21    0.081293  0.000981      19.0  0.0    1340.0  0.0      25.0  0.0
22    0.083588  0.000530      19.0  0.0    1340.0  0.0      25.0  0.0
23    0.084095  0.000000      19.0  0.0    1340.0  0.0      25.0  0.0
24    0.236236       NaN      52.0  NaN    1997.0  NaN      24.0  NaN
25    0.129027  0.004348      52.0  0.0    1997.0  0.0      24.0  0.0
26    0.232056  0.001160      52.0  0.0    1997.0  0.0      24.0  0.0
27    0.236236  0.000000      52.0  0.0    1997.0  0.0      24.0  0.0
28    0.150295       NaN   32352.0  NaN   37003.0  NaN    7585.0  NaN
29    0.000051  0.000034   32352.0  0.0   37003.0  0.0    7585.0  0.0
30    0.087971  0.000496   32352.0  0.0   37003.0  0.0    7585.0  0.0
31    0.155470  0.000293   32352.0  0.0   37003.0  0.0    7585.0  0.0
0     0.022597       NaN   18682.0  NaN   31727.0  NaN    1891.0  NaN
1     0.000063  0.000032   18682.0  0.0   31727.0  0.0    1891.0  0.0
2     0.016817  0.000151   18682.0  0.0   31727.0  0.0    1891.0  0.0
3     0.020773  0.000074   18682.0  0.0   31727.0  0.0    1891.0  0.0
12    0.039249       NaN   33483.0  NaN   33682.0  NaN     899.0  NaN
13    0.000255  0.000045   33483.0  0.0   33682.0  0.0     899.0  0.0
14    0.019427  0.000269   33483.0  0.0   33682.0  0.0     899.0  0.0
15    0.037204  0.000101   33483.0  0.0   33682.0  0.0     899.0  0.0
4     0.061011       NaN   32340.0  NaN   46010.0  NaN     162.0  NaN
5     0.001184  0.000135   32340.0  0.0   46010.0  0.0     162.0  0.0
6     0.044713  0.000190   32340.0  0.0   46010.0  0.0     162.0  0.0
7     0.052358  0.000011   32340.0  0.0   46010.0  0.0     162.0  0.0
8     0.060166       NaN    8911.0  NaN   12051.0  NaN      89.0  NaN
9     0.002109  0.000473    8911.0  0.0   12051.0  0.0      89.0  0.0
10    0.038066  0.000507    8911.0  0.0   12051.0  0.0      89.0  0.0
11    0.050250  0.000073    8911.0  0.0   12051.0  0.0      89.0  0.0

In [163]:
df = df2

In [164]:
import numpy as np

In [165]:


def get_crosstab(df2, key):
    out = []
    default_digits=3
    for m, s in zip(df2[key]["mean"], df2[key]["std"]):
        if np.isnan(s) or s < 10.0**-10:
            out.append(str(np.round(m,default_digits)))
            continue

        digits = 0
        if s > 10.0**(-10):
            while 10.0**digits * s < 1:
                #print(10.0**digits * s, digits)
                digits += 1
        if digits == 0:
            mean = str(int(np.round(m, digits)))
        else:
            mean = str(np.round(m, digits))
        out.append(mean + "("+str(int(np.round(10.0**digits * s))) +")")
    df_tilt = pd.DataFrame()
    df_tilt["abbr"] = df2["abbr"]
    df_tilt["depth"] = df2["depth"]
    tmp = df_tilt["depth"].copy()
    tmp[tmp>=2]=2
    df_tilt["depth"] = tmp
    df_tilt[key] = out
    df= df_tilt.pivot(index="abbr", columns="depth", values=key).reset_index()
    return df[["abbr", -1, 2, 1, 0]]

In [166]:
get_crosstab(df2, "triangles").sort_values(by=['abbr'], key=lambda x: x.map(d))

depth     abbr       -1           2           1           0
8          wea    0.201    0.201(2)    0.184(1)    0.124(1)
4         ht09  157.176  157.178(2)  157.171(6)       77(3)
9           wp   35.808      35.808      35.808       23(6)
5          pri  782.368    782.5(2)    782.7(3)      774(2)
6          rac  1151.35     1151.35   1150.3(7)     1141(7)
7      talk_eo     0.15   0.1499(3)    0.152(1)  1.4e-07(2)
0          dnc    1.922   2.6376(5)     2.52(1)  4.2e-05(3)
3           fb    0.001  0.00146(1)  0.00109(9)  0.00055(2)
1          eu2  291.061   338.73(8)    322.6(7)     1.35(3)
2          eu3    9.036     9.16(2)    8.06(10)     0.96(4)

In [169]:
get_crosstab(df2, "persistence").sort_values(by=['abbr'], key=lambda x: x.map(d))

depth     abbr     -1            2          1           0
8          wea    0.0          0.0        0.0         0.0
4         ht09  0.891  0.89049(10)  0.8899(4)     0.23(3)
9           wp  1.176        1.176      1.176      0.8(2)
5          pri  0.084        0.084  0.0836(5)  0.0813(10)
6          rac  0.236        0.236   0.232(1)    0.129(4)
7      talk_eo   0.15    0.1555(3)   0.088(5)    5e-05(3)
0          dnc  0.023   0.02077(7)  0.0168(2)    6e-05(3)
3           fb  0.039    0.0372(1)  0.0194(3)  0.00026(4)
1          eu2  0.061   0.05236(1)  0.0447(2)   0.0012(1)
2          eu3   0.06   0.05025(7)  0.0381(5)   0.0021(5)

In [168]:
len(df2)

40

In [122]:
df

depth  abbr       -1           2           1         0
0      ht09  157.176  157.178(2)  157.171(6)     77(3)
1       pri  782.368    782.5(2)    782.7(3)    774(2)
2       rac  1151.35     1151.35   1150.3(7)   1141(7)
3       wea    0.201    0.201(2)    0.184(1)  0.124(1)
4        wp   35.808      35.808      35.808     23(6)

In [ ]:
def format_df(df):

In [22]:
df2["abbr"].map({"wea":0, "ht09":1, "wp":2, "pri":3, "rac":4})

0     1
1     1
2     1
3     1
4     3
5     3
6     3
7     3
8     4
9     4
10    4
11    4
12    0
13    0
14    0
15    0
16    2
17    2
18    2
19    2
Name: abbr, dtype: int64